default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: ["--fix", "--show-source"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==23.9.1]
      - id: nbqa-ruff
        additional_dependencies: [ruff==0.0.291]
        args: ["--fix", "--show-source"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [markdown, yaml, toml, json, dockerfile, shell]
        additional_dependencies: ["prettier@3.0.3", "prettier-plugin-sh@0.13.1"]
        args: [--print-width=80, --prose-wrap=always]
